Standardise and simplify tests

diff --git a/.github/workflows/bandit.yml b/.github/workflows/bandit.yml
--- a/.github/workflows/bandit.yml
+++ b/.github/workflows/bandit.yml
@@ -16,7 +16,7 @@ jobs:
       DIFF_REPORTS_FILE: diff_bandit_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -30,14 +30,18 @@ jobs:
       - name: Install bandit
         run: |-
           pip3 install bandit
-          ls -l -a
-          pwd
 
       - name: Run bandit on the new branch
-        run: cd ./${{ env.NEW_BRANCH }}/ && bandit --configfile ./.github/workflows/bandit.config --exit-zero --recursive --output ./../${{ env.NEW_BRANCH_REPORT_FILE }} ./ && cd ./../
+        run: |-
+          bandit --configfile ${{ env.NEW_BRANCH }}/.github/workflows/bandit.conf \
+                 --exit-zero --recursive \
+                 --output ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.NEW_BRANCH }}/
 
       - name: Run bandit on the main branch
-        run: cd ./${{ env.MAIN_BRANCH }}/ && bandit --configfile ./../${{ env.NEW_BRANCH }}/.github/workflows/bandit.config --exit-zero --recursive --output ./../${{ env.MAIN_BRANCH_REPORT_FILE }} ./ && cd ./../
+        run: |-
+          bandit --configfile ${{ env.NEW_BRANCH }}/.github/workflows/bandit.conf \
+                 --exit-zero --recursive \
+                 --output ${{ env.MAIN_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH }}/
 
       - name: Save report results for the new branch
         uses: actions/upload-artifact@v3
@@ -51,7 +55,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: Output diff of 2 reports
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -61,8 +65,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
diff --git a/.github/workflows/cfn_lint.yaml b/.github/workflows/cfn_lint.yaml
--- a/.github/workflows/cfn_lint.yaml
+++ b/.github/workflows/cfn_lint.yaml
@@ -16,7 +16,7 @@ jobs:
       DIFF_REPORTS_FILE: diff_cfnlint_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -27,22 +27,22 @@ jobs:
           repository: awslabs/aws-htc-grid
           path: ${{ env.MAIN_BRANCH }}
 
-      - name: Setup Cloud Formation Linter with Latest Version
+      - name: Setup cfn-lint with latest version
         uses: scottbrenner/cfn-lint-action@v2
         with:
           command: cfn-lint --version
 
       - name: Run cfn_lint on the new branch
-        run: |
-          cfn-lint --config-file ${{ env.NEW_BRANCH }}/.github/workflows/cfn_lint.config \
+        run: |-
+          cfn-lint --config-file ${{ env.NEW_BRANCH }}/.github/workflows/cfn_lint.conf \
                    --format json --output-file ${{ env.NEW_BRANCH_REPORT_FILE }} \
                    ${{ env.NEW_BRANCH }}/deployment/dev_environment_cloud9/**/*.yaml \
                    ${{ env.NEW_BRANCH }}/deployment/init_grid/**/*.yaml
         continue-on-error: true
 
       - name: Run cfn_lint on the main branch
-        run: |
-          cfn-lint --config-file ${{ env.NEW_BRANCH }}/.github/workflows/cfn_lint.config \
+        run: |-
+          cfn-lint --config-file ${{ env.NEW_BRANCH }}/.github/workflows/cfn_lint.conf \
                    --format json --output-file ${{ env.MAIN_BRANCH_REPORT_FILE }} \
                    ${{ env.MAIN_BRANCH }}/deployment/dev_environment_cloud9/**/*.yaml \
                    ${{ env.MAIN_BRANCH }}/deployment/init_grid/**/*.yaml
@@ -60,7 +60,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: Output diff of 2 reports
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -70,8 +70,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
diff --git a/.github/workflows/cfn_nag.yml b/.github/workflows/cfn_nag.yml
--- a/.github/workflows/cfn_nag.yml
+++ b/.github/workflows/cfn_nag.yml
@@ -16,7 +16,7 @@ jobs:
       DIFF_REPORTS_FILE: diff_cfn_nag_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -27,24 +27,19 @@ jobs:
           repository: awslabs/aws-htc-grid
           path: ${{ env.MAIN_BRANCH }}
 
-      - name: Install CFN_Nag
-        run: |-
-          pip3 install awscli 
-          pip3 install cfn-lint             
-          sudo apt-get install jq git -y -q
-          sudo gem install cfn-nag
-          ls -l -a
-          pwd
+      - name: Run cfn_nag on the new branch
+        uses: stelligent/cfn_nag@master
+        with:
+          input_path: ${{ env.NEW_BRANCH }}/deployment/
+          extra_args: -g #-t '..*\/(cfn|cloudformation)\/..*\.yaml' # This flag doesnt seem to be working.
+          output_path: ${{ env.NEW_BRANCH_REPORT_FILE }}
 
-      - name: Run CFN_Nag on the new branch
-        run: |-
-          cd ./${{ env.NEW_BRANCH }}/ && cfn_nag_scan --input-path ./deployment/dev_environment_cloud9/cfn/  >> ./../${{ env.NEW_BRANCH_REPORT_FILE }} || true && cd ./../
-          cd ./${{ env.NEW_BRANCH }}/ && cfn_nag_scan --input-path ./deployment/init_grid/cloudformation/  >> ./../${{ env.NEW_BRANCH_REPORT_FILE }} || true && cd ./../
-
-      - name: Run CFN_Nag on the main branch
-        run: |-
-          cd ./${{ env.MAIN_BRANCH }}/ && cfn_nag_scan --input-path ./deployment/dev_environment_cloud9/cfn/ >> ./../${{ env.MAIN_BRANCH_REPORT_FILE }} || true && cd ./../
-          cd ./${{ env.MAIN_BRANCH }}/ && cfn_nag_scan --input-path ./deployment/init_grid/cloudformation/ >> ./../${{ env.MAIN_BRANCH_REPORT_FILE }} || true && cd ./../
+      - name: Run cfn_nag on main
+        uses: stelligent/cfn_nag@master
+        with:
+          input_path: ${{ env.MAIN_BRANCH }}/deployment/
+          extra_args: -g #-t '..*\/(cfn|cloudformation)\/..*\.yaml' # This flag doesnt seem to be working.
+          output_path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
       - name: Save report results for the new branch
         uses: actions/upload-artifact@v3
@@ -58,7 +53,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: check
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -68,8 +63,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceeding the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
diff --git a/.github/workflows/checkov.yaml b/.github/workflows/checkov.yaml
--- a/.github/workflows/checkov.yaml
+++ b/.github/workflows/checkov.yaml
@@ -16,7 +16,7 @@ jobs:
       DIFF_REPORTS_FILE: diff_checkov_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -31,7 +31,7 @@ jobs:
         uses: bridgecrewio/checkov-action@v12
         with:
           directory: ${{ env.NEW_BRANCH }}
-          config_file: "${{ env.NEW_BRANCH }}/.github/workflows/checkov.config"
+          config_file: "${{ env.NEW_BRANCH }}/.github/workflows/checkov.conf"
           output_format: cli,sarif
           output_file_path: console,${{ env.NEW_BRANCH_REPORT_FILE }}
 
@@ -39,7 +39,7 @@ jobs:
         uses: bridgecrewio/checkov-action@v12
         with:
           directory: ${{ env.MAIN_BRANCH }}
-          config_file: "${{ env.NEW_BRANCH }}/.github/workflows/checkov.config"
+          config_file: "${{ env.NEW_BRANCH }}/.github/workflows/checkov.conf"
           output_format: cli,sarif
           output_file_path: console,${{ env.MAIN_BRANCH_REPORT_FILE }}
 
@@ -61,7 +61,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: Output diff of 2 reports
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -71,8 +71,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
diff --git a/.github/workflows/flake8.yml b/.github/workflows/flake8.yml
--- a/.github/workflows/flake8.yml
+++ b/.github/workflows/flake8.yml
@@ -16,7 +16,7 @@ jobs:
       DIFF_REPORTS_FILE: diff_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -34,10 +34,14 @@ jobs:
           pwd
 
       - name: Run flake8 on the new branch
-        run: cd ./${{ env.NEW_BRANCH }}/ && flake8 --config ./.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.NEW_BRANCH_REPORT_FILE }} && cd ./../
+        run: |-
+          flake8 --config ${{ env.NEW_BRANCH }}/.github/workflows/flake8.conf \
+                 --exit-zero --output-file ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.NEW_BRANCH }}
 
       - name: Run flake8 on the main branch
-        run: cd ./${{ env.MAIN_BRANCH }}/ && flake8 --config ./../${{ env.NEW_BRANCH }}/.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.MAIN_BRANCH_REPORT_FILE }} && cd ./../
+        run: |-
+          flake8 --config ${{ env.NEW_BRANCH }}/.github/workflows/flake8.conf \
+                 --exit-zero --output-file ${{ env.MAIN_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH }}
 
       - name: Save report results for the new branch
         uses: actions/upload-artifact@v3
@@ -51,7 +55,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: check
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -61,8 +65,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceeding the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
diff --git a/.github/workflows/trivy.yaml b/.github/workflows/trivy.yaml
--- a/.github/workflows/trivy.yaml
+++ b/.github/workflows/trivy.yaml
@@ -11,12 +11,12 @@ jobs:
     env:
       NEW_BRANCH: new_branch
       MAIN_BRANCH: main_branch
-      NEW_BRANCH_REPORT_FILE: new_branch_trivy_report_file.sarif
-      MAIN_BRANCH_REPORT_FILE: main_branch_trivy_report_file.sarif
+      NEW_BRANCH_REPORT_FILE: new_branch_trivy_report_file.json
+      MAIN_BRANCH_REPORT_FILE: main_branch_trivy_report_file.json
       DIFF_REPORTS_FILE: diff_trivy_reports.txt
 
     steps:
-      - name: Checkout the modified branch
+      - name: Checkout the new branch
         uses: actions/checkout@v3
         with: 
           path: ${{ env.NEW_BRANCH }}
@@ -34,7 +34,7 @@ jobs:
           scan-ref: ${{ env.NEW_BRANCH }}
           ignore-unfixed: true
           severity: UNKNOWN,MEDIUM,HIGH,CRITICAL
-          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.config"
+          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.conf"
           # output: ${{ env.NEW_BRANCH_REPORT_FILE }} # This flag doesnt seem to be working.
         env:
           TRIVY_OUTPUT: ${{ env.NEW_BRANCH_REPORT_FILE }}
@@ -46,7 +46,7 @@ jobs:
           scan-ref: ${{ env.MAIN_BRANCH }}
           ignore-unfixed: true
           severity: UNKNOWN,MEDIUM,HIGH,CRITICAL
-          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.config"
+          trivy-config: "${{ env.NEW_BRANCH }}/.github/workflows/trivy.conf"
           # output: ${{ env.MAIN_BRANCH_REPORT_FILE }} # This flag doesnt seem to be working.
         env:
           TRIVY_OUTPUT: ${{ env.MAIN_BRANCH_REPORT_FILE }}
@@ -70,7 +70,7 @@ jobs:
           name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
           path: ${{ env.MAIN_BRANCH_REPORT_FILE }}
 
-      - name: Output diff of 2 reports
+      - name: Generate the diff of reports between main and the new branch
         run: |-
           diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true
 
@@ -80,8 +80,9 @@ jobs:
           name: ${{ env.DIFF_REPORTS_FILE }}
           path: ${{ env.DIFF_REPORTS_FILE }}
 
-      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch.
+      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
         run: |-          
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
-          ls -l -a
-          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }}
+          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
+            echo "Warning: New branch has more errors!"
+            exit 1
+          fi
