Update flake8.yml

diff --git a/.github/workflows/flake8.yml b/.github/workflows/flake8.yml
--- a/.github/workflows/flake8.yml
+++ b/.github/workflows/flake8.yml
@@ -65,7 +65,8 @@ jobs:
           path: ${{ env.DIFF_REPORTS_FILE }}
           
       - name: Verify that the number of errors in the new branch does not exceeding the number of existing errors in the main branch.
-        run: |-
-          echo 'if [ "$(wc -l < $1 )" -gt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
+        run: |-          
+          echo 'if [ "$(wc -l < $1 )" -lt "$(wc -l < $2 )" ]; then echo "Warning New branch has more errors!"; exit 1; fi; exit 0' >> script.sh
+          ls -l -a
           bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }}. ${{ env.MAIN_BRANCH_REPORT_FILE }}
               
